name: jest

on:
  push:
  pull_request:

jobs:
  jest:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.repository_owner != github.event.pull_request.head.repo.owner.login }}

    strategy:
      matrix:
        node-version: [14.x, 16]

    steps:
      - name: Checkout repository
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # tag=v3.0.1

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # tag=v3.1.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies with yarn
        run: yarn install --frozen-lockfile

      - name: Jest
        run: yarn jest
