name: jest

on:
  push:
  pull_request:

jobs:
  jest:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.repository_owner != github.event.pull_request.head.repo.owner.login }}

    strategy:
      matrix:
        node-version: [14.x, 16]

    steps:
      - name: Checkout repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # tag=v3.1.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies with yarn
        run: yarn install --frozen-lockfile

      - name: Jest
        run: yarn jest
